//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxCalculator.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxCalculator.Resource.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Should be greater than 18.
        /// </summary>
        internal static string AgeGreaterThan18 {
            get {
                return ResourceManager.GetString("AgeGreaterThan18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Cannot be Greater than 100.
        /// </summary>
        internal static string AgeLessThan100 {
            get {
                return ResourceManager.GetString("AgeLessThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Date Properly in given Format:               .
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be greater than 31, Please Enter correctly.
        /// </summary>
        internal static string DateValidation {
            get {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Birth Date is Greater than Todays Date.
        /// </summary>
        internal static string dayGreater {
            get {
                return ResourceManager.GetString("dayGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Should not Start with Empty Space and Atleast one character should be there .
        /// </summary>
        internal static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Number.
        /// </summary>
        internal static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Y or N.
        /// </summary>
        internal static string EnterYorN {
            get {
                return ResourceManager.GetString("EnterYorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!!!!!!!!!!!!!!!!!!!!!!!!!!!.
        /// </summary>
        internal static string Exclamation {
            get {
                return ResourceManager.GetString("Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender should be Male or Female.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male|Female.
        /// </summary>
        internal static string GenderOption {
            get {
                return ResourceManager.GetString("GenderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your investment and Loan should not be greater than Income!!!!!!!!.
        /// </summary>
        internal static string GreaterThanIncome {
            get {
                return ResourceManager.GetString("GreaterThanIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value less than 10000000000.
        /// </summary>
        internal static string GreaterThanLimit {
            get {
                return ResourceManager.GetString("GreaterThanLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Value.
        /// </summary>
        internal static string IncomeNullEntry {
            get {
                return ResourceManager.GetString("IncomeNullEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month cannot be greater than 12, Please Enter correctly.
        /// </summary>
        internal static string MonthValidation {
            get {
                return ResourceManager.GetString("MonthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name Properly.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter only Alphabets in Name, Name cannot contain Digits.
        /// </summary>
        internal static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Month does not Contain 30th Date please Enter Correct Date.
        /// </summary>
        internal static string No30thDate {
            get {
                return ResourceManager.GetString("No30thDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Month does not Contain 31 Date please Enter Correct Date.
        /// </summary>
        internal static string No31Days {
            get {
                return ResourceManager.GetString("No31Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Year is not a Leap Year therefore there is no 29th Feb in that Year.
        /// </summary>
        internal static string NotALeapYear {
            get {
                return ResourceManager.GetString("NotALeapYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a positive number.
        /// </summary>
        internal static string PositiveInteger {
            get {
                return ResourceManager.GetString("PositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Income Value should Not be Zero.
        /// </summary>
        internal static string ShouldNotBeZero {
            get {
                return ResourceManager.GetString("ShouldNotBeZero", resourceCulture);
            }
        }
    }
}
